/**
 * Swizzled from @docusaurus/theme-classic to add a section crumb.
 *
 * Every docs section here is an `autogenerated` sidebar over a flat folder, so
 * Docusaurus has no category to put between the home crumb and the page, and
 * every page reads "Home > Overview". This adds the section itself — the name
 * a reader would call the hotsite — giving "Home > Drools > Overview".
 */
import React from "react";
import clsx from "clsx";
import { ThemeClassNames } from "@docusaurus/theme-common";
import {
  useSidebarBreadcrumbs,
  useHomePageRoute,
  useDocsSidebar,
} from "@docusaurus/theme-common/internal";
import Link from "@docusaurus/Link";
import { translate } from "@docusaurus/Translate";
import HomeBreadcrumbItem from "@theme/DocBreadcrumbs/Items/Home";

import { findSectionBySidebar } from "@site/src/componentSections";
import styles from "./styles.module.css";

function BreadcrumbsItemLink({
  children,
  href,
  isLast,
}: {
  children: React.ReactNode;
  href?: string;
  isLast: boolean;
}) {
  const className = "breadcrumbs__link";
  if (isLast) {
    return (
      <span className={className} itemProp="name">
        {children}
      </span>
    );
  }
  return href ? (
    <Link className={className} href={href} itemProp="item">
      <span itemProp="name">{children}</span>
    </Link>
  ) : (
    <span className={className}>{children}</span>
  );
}

function BreadcrumbsItem({
  children,
  active,
  index,
  addMicrodata,
}: {
  children: React.ReactNode;
  active?: boolean;
  index: number;
  addMicrodata?: boolean;
}) {
  return (
    <li
      {...(addMicrodata && {
        itemScope: true,
        itemProp: "itemListElement",
        itemType: "https://schema.org/ListItem",
      })}
      className={clsx("breadcrumbs__item", {
        "breadcrumbs__item--active": active,
      })}
    >
      {children}
      <meta itemProp="position" content={String(index + 1)} />
    </li>
  );
}

export default function DocBreadcrumbs(): JSX.Element | null {
  const breadcrumbs = useSidebarBreadcrumbs();
  const homePageRoute = useHomePageRoute();
  const sidebar = useDocsSidebar();

  if (!breadcrumbs) {
    return null;
  }

  const section = findSectionBySidebar(sidebar?.name);
  const items = section
    ? [
        { type: "link" as const, label: section.label, href: section.basePath },
        ...breadcrumbs,
      ]
    : breadcrumbs;

  return (
    <nav
      className={clsx(
        ThemeClassNames.docs.docBreadcrumbs,
        styles.breadcrumbsContainer,
      )}
      aria-label={translate({
        id: "theme.docs.breadcrumbs.navAriaLabel",
        message: "Breadcrumbs",
        description: "The ARIA label for the breadcrumbs",
      })}
    >
      <ul
        className="breadcrumbs"
        itemScope
        itemType="https://schema.org/BreadcrumbList"
      >
        {homePageRoute && <HomeBreadcrumbItem />}
        {items.map((item, idx) => {
          const isLast = idx === items.length - 1;
          const href =
            item.type === "category" && item.linkUnlisted
              ? undefined
              : item.href;
          return (
            <BreadcrumbsItem
              key={idx}
              active={isLast}
              index={idx}
              addMicrodata={!!href}
            >
              <BreadcrumbsItemLink href={href} isLast={isLast}>
                {item.label}
              </BreadcrumbsItemLink>
            </BreadcrumbsItem>
          );
        })}
      </ul>
    </nav>
  );
}
