name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SonataFlow repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-kogito-docs
          ref: 10.0.x
          path: sonataflow-docs

      - name: Build Sonataflow documentation
        run: |
          cd sonataflow-docs
          npm run install-build

      - name: Checkout Drools repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-drools
          ref: 10.0.x
          path: drools

      - name: Build Drools documentation
        run: |
          cd drools/drools-docs
          mvn -B clean install

      - name: Checkout Kogito documentation repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-docs
          ref: 10.0.x
          path: kogito-docs

      - name: Build Kogito documentation
        run: |
          cd kogito-docs
          mvn -B clean install -Dfull

      - name: Checkout Apache KIE Website repository
        uses: actions/checkout@v4
        with:
          path: incubator-kie-website

      - name: Copy Sonataflow docs to Apache KIE static folder
        run: |
          mkdir -p incubator-kie-website/static/sonataflow-docs
          cp -r sonataflow-docs/build/site/* incubator-kie-website/static/sonataflow-docs

      - name: Copy Drools docs to Apache KIE static folder
        run: |
          mkdir -p incubator-kie-website/static/drools-docs
          cp -r drools/drools-docs/target/website/docs/* incubator-kie-website/static/drools-docs

      - name: Copy Kogito docs to Apache KIE static folder
        run: |
          mkdir -p incubator-kie-website/static/kogito-docs
          cp -r kogito-docs/doc-content/apache-kie-kogito/target/generated-docs/html_single/* incubator-kie-website/static/kogito-docs

      - name : Build Apache Kie Website
        run: |
          cd incubator-kie-website
          npm install
          npm run build
          cp .asf.yaml build/.asf.yaml

      - name: Archive Apache KIE Website for preview
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: apache-kie-website
          path: incubator-kie-website/build
          overwrite: true

      - name: Deploy Apache KIE Website
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: incubator-kie-website/build
          publish_branch: deploy
